version: "3"
services:
  jenkins:
    image: jenkinsci/jenkins:${TAG}
    container_name: jenkins-blueocean
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - ANDROID_HOME=/opt/android-linux-sdk
      - ANDROID_SDK_HOME=/var/jenkins_home/tmp/android
      - GRADLE_USER_HOME=/var/jenkins_home/tools/gradle
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - jenkins_home:/var/jenkins_home
      - ${ANDROID_HOME}:/opt/android-linux-sdk

volumes:
  jenkins_home: